version: '3.8'

services:
  # --- NÓ 01 ---
  db1:
    image: mysql:8.0
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddb_distributed
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      ddb_net:
        ipv4_address: 10.10.0.10

  node1:
    build: .
    container_name: node1
    depends_on:
      - db1
    environment:
      - MY_IP=10.10.0.101
      - ALL_NODES=10.10.0.101,10.10.0.102,10.10.0.103
      - DB_URL=jdbc:mysql://10.10.0.10:3306/ddb_distributed
    ports:
      - "5001:5000"
    networks:
      ddb_net:
        ipv4_address: 10.10.0.101

  # --- NÓ 02 ---
  db2:
    image: mysql:8.0
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddb_distributed
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      ddb_net:
        ipv4_address: 10.10.0.20

  node2:
    build: .
    container_name: node2
    depends_on:
      - db2
    environment:
      - MY_IP=10.10.0.102
      - ALL_NODES=10.10.0.101,10.10.0.102,10.10.0.103
      - DB_URL=jdbc:mysql://10.10.0.20:3306/ddb_distributed
    ports:
      - "5002:5000"
    networks:
      ddb_net:
        ipv4_address: 10.10.0.102

  # --- NÓ 03 ---
  db3:
    image: mysql:8.0
    container_name: db3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddb_distributed
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      ddb_net:
        ipv4_address: 10.10.0.30

  node3:
    build: .
    container_name: node3
    depends_on:
      - db3
    environment:
      - MY_IP=10.10.0.103
      - ALL_NODES=10.10.0.101,10.10.0.102,10.10.0.103
      - DB_URL=jdbc:mysql://10.10.0.30:3306/ddb_distributed
    ports:
      - "5003:5000"
    networks:
      ddb_net:
        ipv4_address: 10.10.0.103

networks:
  ddb_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24